const selectors = {
    "email": ".flex-dir-col > :nth-child(1) > .input > input",
    "password": ".mt-9 > .input-container > .input > input",
    "loginButton": ".mt-10",
    "popUp": "[data-qa='close']",
    "navHome": ":nth-child(1) > .anchor > .sidebar-link > .flex >",
    "navCreateContract": ":nth-child(2) > .anchor > .sidebar-link > .flex > .sidebar-option-p",
    "navContracts": ":nth-child(3) > .anchor > .sidebar-link > .flex",
    "navReports": ":nth-child(4) > .anchor > .sidebar-link > .flex >",
    "navCompDoc": ":nth-child(5) > .anchor > .sidebar-link > .flex",
    "navInvAndReceipts": ":nth-child(6) > .anchor > .sidebar-link > .flex",
    "navTaxes": ":nth-child(7) > .anchor > .sidebar-link > .flex",
    "navTeamSettings": ":nth-child(8) > .anchor > .sidebar-link > .flex",
    "navPerks": ":nth-child(9) > .anchor > .sidebar-link > .flex",
    "fixedRate": ":nth-child(1) > .anchor > .box",
    "contractName": "[name='name']",
    "jobTitle": "[name='jobTitle']",
    "suggestionBox": ".suggestions-box",
    "suggestionOption": ".suggestions-option",
    "seniorityLevel": "[data-qa='selector-seniority-level']",
    "level": "#react-select-4-option-3",
    "textField": ".textarea",
    "predefineScope": "h6.color-primary",
    "qa": ".scopes-container > :nth-child(14)",
    "calenderInput": ".deel-ui__calendar-input-container__input_content",
    "dateNow": ".react-calendar__tile--now",
    "taxResidence": ":nth-child(1) > .deel-ui__stack_vertical > .input-container > .flex > .deel-ui__select > .deel-ui__select__input-container > .deel-ui__select__control > .deel-ui__select__value-container",
    "selectorContainer": ".deel-ui__select__menu",
    "state": ":nth-child(2) > .deel-ui__select__input-container > .deel-ui__select__control > .deel-ui__select__value-container",
    "selectedState": ".deel-ui__select__menu-list",
    "next": "[type='submit']",
    "currency": "[data-qa='currency-select']",
    "rate": "[name='rate']",
    "cycle": ":nth-child(2) > .flex > .deel-ui__select > .deel-ui__select__input-container > .deel-ui__select__control > .deel-ui__select__value-container",
    "firstPaymentDate": "[data-qa='selector-first-payment-date']",
    "proRata": "[data-qa='tab-button-prorata']",
    "proRataAmount": "[data-qa='pro-rata-amount']",
    "terminationCard" : "[data-qa='termination-date-card']",
    "noticePeriod" : "[data-qa='days-of-notice-card']",
    "terminationCalender" : ".calendar-input",
    "submit" :  ":nth-child(6) > .button",
    "create" : ":nth-child(5) > .button"
}
module.exports = selectors